# Don't forget to update permissions and add this repo in
# https://app.bors.tech/repositories so bors can see the new repo!

status = [
  "all_tests",
  "rust_lints",
]
timeout_sec = 600
delete_merged_branches = true
