name: "CI"
# This workflow is triggered on all pushes to the repository, or on Friday night.
on:
  pull_request: {}
  push:
    branches:
      - master
      - staging
      - trying
  schedule:
    - cron: '0 23 * * FRI'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_toolchain: [nightly, stable]
        cargo_args:
          - "--no-default-features --features no_std"
          - ""
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust_toolchain }}
            override: true
            profile: minimal
      - name: "cargo test"
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: ${{ matrix.cargo_args }}
          toolchain: ${{ matrix.rust_toolchain }}

  all_tests:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Mark the job as a success
        run: exit 0

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: "cargo fmt"
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: "-v -- --check"

  cargo_deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: "cargo deny"
      uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: "check all"

  cargo_clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: "cargo clippy"
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: -- -D warnings

  cargo_bench:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: test
    steps:
      - uses: actions/checkout@v3.0.2
      - name: "cargo bench"
        uses: actions-rs/cargo@v1.0.3
        with:
          command: bench
