name: Prepare for a new release to crates.io
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true
        type: string

jobs:
  make-release-pr:
    permissions:
      id-token: write # Enable OIDC
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: chainguard-dev/actions/setup-gitsign@main
      - name: Install cargo-release
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-release
      - name: Install cargo-semver-checks
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-semver-checks
      - uses: cargo-bins/release-pr@v2
        id: pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
          check-semver: true
          crate-release-all: true # all in workspace
      - uses: actions-ecosystem/action-regex-match@v2
        id: pr-id
        with:
          text: ${{ steps.pr.outputs.pr-url }}
          regex: "/pull/([0-9]+)$"
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: release
          number: ${{ steps.pr-id.outputs.group1 }}
